### ISSUE TITLE
Status of JsonPath support

### ISSUE THREAD

**Issue by ghxiao** [gabrielelana/mongodb-shell-extensions#2]
Hi,

First, thanks for your amazing project!

I would like to ask what is the status of jsonPath support? I saw that in the README there is an empty session named JsonPath. I am curious to know the status and the plan regarding jsonPath support.

Cheers,

**Comment by gabrielelana** [comment]
@ghxiao Thanks! JSONPath is fully supported, I have updated the README, have a look :wink:

**Comment by ghxiao** [comment]
Brilliant!
